os: linux
dist: focal

services:
  - docker

before_install:
  - docker build -t ryzhenskiy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ryzhenskiy/docker-react npm test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'frontend'
  env: 'Frontend-env'
  bucket_name: 'elasticbeanstalk-us-east-1-992382413944'
  bucket_path: 'frontend'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
